### ISSUE TITLE
Question: Bind to a key or add to the context menu?

### ISSUE THREAD

**Issue by Xylemon** [jpfleury/corbeille-spacefm#1]
I was wondering if there was anyway to use this plugin via a key bind (rebind the delete key to use this plugin instead) or a way to add the "Trash" menu from the "Plugins" menu into the context menu?

**Comment by jpfleury** [comment]
Hi,

To add "Trash" in the context menu:
1. In the "Plugins" menu, right-click on "Trash" and choose "Copy".
2. Right-click on the file area to display the context menu.
3. Right-click on a menu item and choose "Paste".

The menu "Trash" will be added below this menu item.

If you want the menu item "Move to Trash" directly in the context menu instead of a submenu:
1. Right-click on a file, then right-click on the menu item "Move to Trash".
2. Copy it.
3. Right-click on a menu item and choose "Paste".

The menu item "Move to Trash" will be added below this menu item.

To use the key shortcut "Delete":
1. Right-click on a file, then right-click on the menu item "Move to Trash".
2. Choose "Key Shortcut".
3. Press "Delete" and apply changes.

**Comment by Xylemon** [comment]
Thank you! I had no idea you could do this in SpaceFM, learn something everyday.

**Comment by thierrybo** [comment]
same for me, you saved my day!
